name: island_diary
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  audioplayers: ^6.6.0
  file_picker: ^8.1.7
  flutter_animate: ^4.5.2
  shared_preferences: ^2.5.4
  speech_to_text: ^7.3.0
  permission_handler: ^12.0.1
  image_picker: ^1.2.1
  flutter_colorpicker: ^1.1.0
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  uuid: ^4.5.3
  intl: ^0.20.2
  share_plus: ^12.0.1
  path_provider: ^2.1.5
  pdf: ^3.11.1
  printing: ^5.13.0
  wechat_assets_picker: ^9.5.0
  video_player: ^2.9.2
  lunar: ^1.7.8
  fl_chart: ^1.2.0
  flutter_windowmanager_plus: ^1.0.1
  camera: ^0.11.0+2
  path: ^1.9.0
  http: ^1.1.0
  dio: ^5.9.2
  archive: ^4.0.9
  flutter_staggered_grid_view: ^0.7.0
  image: ^4.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/decoration/furniture/
    - assets/images/decoration/floors/
    - assets/images/decoration/carpets/
    - assets/images/decoration/music/
    - assets/images/decoration/kitchen/
    - assets/images/decoration/livingRoom/
    - assets/images/decoration/sofa/
    - assets/images/decoration/table/
    - assets/images/decoration/houseplant/
    - assets/images/decoration/wall/
    - assets/images/decoration/homeDecor/
    - assets/images/decoration/shelving/
    - assets/images/decoration/wardrobe/
    - assets/images/decoration/window/
    - assets/images/decoration/bed/
    - assets/images/decoration/animal/
    - assets/images/decoration/door/
    - assets/images/decoration/refrigerators/
    - assets/images/decoration/clothes/
    - assets/images/note/
    - assets/images/icons/
    - assets/icons/
    - assets/images/emoji/
    - assets/images/emoji/decorate/
    - assets/images/emoji/glasses/
    - assets/images/emoji/wechat/face/
    - assets/images/emoji/wechat/gesture/
    - assets/images/emoji/wechat/animal/
    - assets/images/emoji/wechat/blessing/
    - assets/images/emoji/wechat/other/
    - assets/images/emoji/medal/
    - assets/images/event/
    - assets/images/test/
    - assets/audio/
    - assets/fonts/
    - assets/images/emoji/yunzhi/
    - assets/images/emoji/shuangjian/
    - assets/images/emoji/dushou/
    - assets/images/emoji/lingxi/
    - assets/images/sticker/

  fonts:
    - family: FZKai
      fonts:
        - asset: assets/fonts/FangZhengKaiTiJianTi-1.ttf
    - family: LXGWWenKai
      fonts:
        - asset: assets/fonts/LXGWWenKai-Regular.ttf
        - asset: assets/fonts/LXGWWenKai-Medium.ttf
          weight: 500
    - family: Alibaba
      fonts:
        - asset: assets/fonts/Alibaba-PuHuiTi-Heavy.ttf
    - family: Douyin
      fonts:
        - asset: assets/fonts/DouyinSansBold.otf
    - family: JingNan
      fonts:
        - asset: assets/fonts/JingNanBoBoHei-Bold-2.ttf
    - family: Nishiki
      fonts:
        - asset: assets/fonts/nishiki-teki.ttf
    - family: Zhi Mang Xing
      fonts:
        - asset: assets/fonts/FangZhengKaiTiJianTi-1.ttf
    - family: WanWeiWei
      fonts:
        - asset: assets/fonts/我爱万伟伟手写体.ttf
    - family: CangErGuoMiao
      fonts:
        - asset: assets/fonts/【MianFei】CangJiGaoDeGuoMiaoHei-CJgaodeguomh-2.ttf
    - family: MaoKenZhuYuan
      fonts:
        - asset: assets/fonts/MaoKenZhuYuanTi-MaokenZhuyuanTi-2.ttf
    - family: ArphicKaiti
      fonts:
        - asset: assets/fonts/gkai00mp-2.ttf
