# JVM 内存与性能优化参数
org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError

# 启用 AndroidX 支持
android.useAndroidX=true

# 禁用 Kotlin 增量编译（避免 Windows 跨盘符 C:pub-cache 与 D:项目路径计算报错）
kotlin.incremental=false

# 开启 Gradle 守护进程
org.gradle.daemon=true

# 开启并行编译与构建缓存
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.vfs.watch=true

# 由 Flutter 迁移工具自动添加的标记
android.builtInKotlin=false
android.newDsl=false
android.nonFinalResIds=true



