import 'package:flutter/material.dart';
import '../models/mood_item.dart';

// 这里的顺序必须与 MoodSelectorHeader 中的 moods 列表完全一致
List<MoodItem> kMoods = [
  // 0: 开心 (原索引 7)
  const MoodItem(
    label: '开心',
    imagePath: 'assets/images/icons/select8.png',
    angle: 4,
    imageRotation: 0,
    imageTop: 10,
    imageLeft: 72,
    width: 175,
    height: 230,
    scale: 0.48,
    iconPath: 'assets/images/icons/sun.png',
    iconSize: 46,
    fontSize: 14,
    iconOffset: Offset(33, -88),
    textOffset: Offset(33, -60),
    glowColor: Color(0xFFFFE484),
    popAngle: -67.2,
  ),
  // 1: 平静 (原索引 4)
  const MoodItem(
    label: '平静',
    imagePath: 'assets/images/icons/select5.png',
    angle: 180,
    imageRotation: 180,
    imageTop: -294,
    imageLeft: -88,
    width: 306,
    height: 420,
    scale: 0.274,
    iconPath: 'assets/images/icons/leaf.png',
    iconSize: 56,
    fontSize: 14,
    iconOffset: Offset(34, 78),
    textOffset: Offset(38, 112),
    glowColor: Color(0xFFA4D4E4),
    popAngle: 63.85,
  ),
  // 2: 低落 (原索引 6 - 悲伤)
  const MoodItem(
    label: '低落',
    imagePath: 'assets/images/icons/select7.png',
    angle: 270,
    imageRotation: 90,
    imageTop: -158,
    imageLeft: 180,
    width: 245,
    height: 181,
    scale: 0.52,
    iconPath: 'assets/images/icons/raindrop.png',
    iconSize: 58,
    fontSize: 14,
    iconOffset: Offset(86, -42),
    textOffset: Offset(96, -17),
    glowColor: Color(0xFF84A4E4),
    popAngle: -21,
  ),
  // 3: 烦躁 (原索引 5 - 愤怒)
  const MoodItem(
    label: '烦躁',
    imagePath: 'assets/images/icons/select6.png',
    angle: 225,
    imageRotation: 134,
    imageTop: -176,
    imageLeft: -58,
    width: 301,
    height: 221,
    scale: 0.38,
    iconPath: 'assets/images/icons/angry.png',
    iconSize: 56,
    fontSize: 14,
    iconOffset: Offset(86, 28),
    textOffset: Offset(95, 54),
    glowColor: Color(0xFFFF8484),
    popAngle: 20.25,
  ),
  // 4: 疲惫 (暂用 select2 - 厌恶的配置)
  const MoodItem(
    label: '疲惫',
    imagePath: 'assets/images/icons/select2.png',
    angle: 315,
    imageRotation: 40,
    imageTop: 13,
    imageLeft: 60,
    width: 324,
    height: 237,
    scale: 0.34,
    iconPath: 'assets/images/icons/upset.png',
    iconSize: 40,
    fontSize: 14,
    iconOffset: Offset(-74, -38),
    textOffset: Offset(-80, -14),
    glowColor: Color(0xFFC4A4E4),
    popAngle: -154.3,
  ),
  // 5: 惊喜 (原索引 3)
  const MoodItem(
    label: '惊喜',
    imagePath: 'assets/images/icons/select4.png',
    angle: 225,
    imageRotation: 135,
    imageTop: -178,
    imageLeft: 123,
    width: 230,
    height: 345,
    scale: 0.35,
    iconPath: 'assets/images/icons/star.png',
    iconSize: 40,
    fontSize: 14,
    iconOffset: Offset(-28, 78),
    textOffset: Offset(-32, 112),
    glowColor: Color(0xFFFFC484),
  ),
  // 6: 害羞 (暂用 select1 - 期待的配置)
  const MoodItem(
    label: '害羞',
    imagePath: 'assets/images/icons/select1.png',
    angle: 0,
    imageRotation: 0,
    imageTop: 8,
    imageLeft: -78,
    width: 205,
    height: 286,
    scale: 0.38,
    iconPath: 'assets/icons/shy.png',
    iconSize: 40,
    fontSize: 14,
    iconOffset: Offset(-28, -84),
    textOffset: Offset(-26, -60),
    glowColor: Color(0xFFF06292),
    popAngle: -110.0,
  ),
  // 7: 焦虑 (原索引 2 - 恐惧)
  const MoodItem(
    label: '焦虑',
    imagePath: 'assets/images/icons/select3.png',
    angle: 270,
    imageRotation: 90,
    imageTop: -60,
    imageLeft: 72,
    width: 324,
    height: 241,
    scale: 0.33,
    iconPath: 'assets/icons/anxious.png',
    iconSize: 52,
    fontSize: 14,
    iconOffset: Offset(-76, 28),
    textOffset: Offset(-84, 54),
    glowColor: Color(0xFF90A4AE),
    popAngle: 158.45,
  ),
  // 8: 委屈 (暂用 select7 - 悲伤的配置)
  const MoodItem(
    label: '委屈',
    imagePath: 'assets/images/icons/select7.png',
    angle: 270,
    imageRotation: 90,
    imageTop: -158,
    imageLeft: 180,
    width: 245,
    height: 181,
    scale: 0.52,
    iconPath: 'assets/icons/wronged.png',
    iconSize: 58,
    fontSize: 14,
    iconOffset: Offset(86, -42),
    textOffset: Offset(96, -17),
    glowColor: Color(0xFF9575CD),
    popAngle: -21,
  ),
  // 9: 无聊 (暂用 select5 - 平静的配置)
  const MoodItem(
    label: '无聊',
    imagePath: 'assets/images/icons/select5.png',
    angle: 180,
    imageRotation: 180,
    imageTop: -294,
    imageLeft: -88,
    width: 306,
    height: 420,
    scale: 0.274,
    iconPath: 'assets/icons/bored.png',
    iconSize: 56,
    fontSize: 14,
    iconOffset: Offset(34, 78),
    textOffset: Offset(38, 112),
    glowColor: Color(0xFFA1887F),
    popAngle: 63.85,
  ),
  // 10: 期待 (原索引 0)
  const MoodItem(
    label: '期待',
    imagePath: 'assets/images/icons/select1.png',
    angle: 0,
    imageRotation: 0,
    imageTop: 8,
    imageLeft: -78,
    width: 205,
    height: 286,
    scale: 0.38,
    iconPath: 'assets/icons/expect.png',
    iconSize: 40,
    fontSize: 14,
    iconOffset: Offset(-28, -84),
    textOffset: Offset(-26, -60),
    glowColor: Color(0xFFFFB74D),
    popAngle: -110.0,
  ),
];
