part of 'mascot_decoration.dart';

/// 耳饰装扮数据
const List<MascotDecoration> _earringDecorations = [
  MascotDecoration(
    id: 'earring_honey_bear_heart',
    name: '蜜糖熊心',
    path: 'assets/images/emoji/arrings/arrings.png',
    leftPath: 'assets/images/emoji/arrings/arrings1_l.png',
    rightPath: 'assets/images/emoji/arrings/arrings1_r.png',
    description: '甜甜的蜜糖色小熊耳饰，爱心满满，给可爱的小软增添双倍的精致与治愈。',
    rarity: MascotRarity.rare,
    category: MascotDecorationCategory.face,
    keepEars: true,
    defaultConfig: MascotDecorationConfig(
      leftOffset: Offset(-55, 30),
      leftScale: 0.65,
      rightOffset: Offset(55, 30),
      rightScale: 0.65,
    ),
    characterConfigs: {
      'assets/images/emoji/marshmallow.png': MascotDecorationConfig(
        leftOffset: Offset(-70, 50),
        leftScale: 0.3,
        rightOffset: Offset(70, 50),
        rightScale: 0.3,
      ),
      'assets/images/emoji/marshmallow2.png': MascotDecorationConfig(
        leftOffset: Offset(-70, 40),
        leftScale: 0.3,
        rightOffset: Offset(70, 40),
        rightScale: 0.3,
      ),
      'assets/images/emoji/marshmallow3.png': MascotDecorationConfig(
        leftOffset: Offset(-70, 60),
        leftScale: 0.3,
        rightOffset: Offset(70, 60),
        rightScale: 0.3,
      ),
      'assets/images/emoji/marshmallow4.png': MascotDecorationConfig(
        leftOffset: Offset(-68, 60),
        leftScale: 0.3,
        rightOffset: Offset(70, 60),
        rightScale: 0.3,
      ),
    },
  ),
  MascotDecoration(
    id: 'earring_summer_melon_knot',
    name: '夏日瓜瓜结',
    path: 'assets/images/emoji/arrings/arrings2.png',
    leftPath: 'assets/images/emoji/arrings/arrings2_l.png',
    rightPath: 'assets/images/emoji/arrings/arrings2_r.png',
    description: '充满夏日清爽气息的瓜瓜结耳饰，带给你一整夏的清凉与好心情。',
    rarity: MascotRarity.rare,
    category: MascotDecorationCategory.face,
    keepEars: true,
    defaultConfig: MascotDecorationConfig(
      leftOffset: Offset(-55, 30),
      leftScale: 0.65,
      rightOffset: Offset(55, 30),
      rightScale: 0.65,
    ),
    characterConfigs: {
      'assets/images/emoji/marshmallow.png': MascotDecorationConfig(
        leftOffset: Offset(-70, 50),
        leftScale: 0.3,
        rightOffset: Offset(70, 50),
        rightScale: 0.3,
      ),
      'assets/images/emoji/marshmallow2.png': MascotDecorationConfig(
        leftOffset: Offset(-70, 40),
        leftScale: 0.3,
        rightOffset: Offset(70, 40),
        rightScale: 0.3,
      ),
      'assets/images/emoji/marshmallow3.png': MascotDecorationConfig(
        leftOffset: Offset(-70, 60),
        leftScale: 0.3,
        rightOffset: Offset(70, 60),
        rightScale: 0.3,
      ),
      'assets/images/emoji/marshmallow4.png': MascotDecorationConfig(
        leftOffset: Offset(-68, 60),
        leftScale: 0.3,
        rightOffset: Offset(70, 60),
        rightScale: 0.3,
      ),
    },
  ),
  MascotDecoration(
    id: 'earring_starry_cat_ear_drop',
    name: '星夜猫耳朵坠',
    path: 'assets/images/emoji/arrings/arrings3.png',
    leftPath: 'assets/images/emoji/arrings/arrings3_l.png',
    rightPath: 'assets/images/emoji/arrings/arrings3_r.png',
    description: '深邃的星夜蓝色猫耳耳坠，摇曳着点点星光，神秘而又充满灵气。',
    rarity: MascotRarity.epic,
    category: MascotDecorationCategory.face,
    keepEars: true,
    defaultConfig: MascotDecorationConfig(
      leftOffset: Offset(-55, 30),
      leftScale: 0.65,
      rightOffset: Offset(55, 30),
      rightScale: 0.65,
    ),
    characterConfigs: {
      'assets/images/emoji/marshmallow.png': MascotDecorationConfig(
        leftOffset: Offset(-68, 50),
        leftScale: 0.4,
        rightOffset: Offset(68, 50),
        rightScale: 0.4,
      ),
      'assets/images/emoji/marshmallow2.png': MascotDecorationConfig(
        leftOffset: Offset(-70, 28),
        leftScale: 0.4,
        rightOffset: Offset(70, 28),
        rightScale: 0.4,
      ),
      'assets/images/emoji/marshmallow3.png': MascotDecorationConfig(
        leftOffset: Offset(-68, 60),
        leftScale: 0.4,
        rightOffset: Offset(68, 60),
        rightScale: 0.4,
      ),
      'assets/images/emoji/marshmallow4.png': MascotDecorationConfig(
        leftOffset: Offset(-68, 50),
        leftScale: 0.4,
        rightOffset: Offset(68, 50),
        rightScale: 0.4,
      ),
    },
  ),
  MascotDecoration(
    id: 'earring_orange_kitty_stud',
    name: '橘香喵喵耳坠',
    path: 'assets/images/emoji/arrings/arrings4.png',
    leftPath: 'assets/images/emoji/arrings/arrings4_l.png',
    rightPath: 'assets/images/emoji/arrings/arrings4_r.png',
    description: '散发着清甜橘香的小猫咪造型耳坠，精致玲珑，戴上它心情也变得格外明媚。',
    rarity: MascotRarity.rare,
    category: MascotDecorationCategory.face,
    keepEars: true,
    defaultConfig: MascotDecorationConfig(
      leftOffset: Offset(-55, 30),
      leftScale: 0.65,
      rightOffset: Offset(55, 30),
      rightScale: 0.65,
    ),
    characterConfigs: {
      'assets/images/emoji/marshmallow.png': MascotDecorationConfig(
        leftOffset: Offset(-64, 50),
        leftScale: 0.3,
        rightOffset: Offset(64, 50),
        rightScale: 0.3,
      ),
      'assets/images/emoji/marshmallow2.png': MascotDecorationConfig(
        leftOffset: Offset(-70, 30),
        leftScale: 0.3,
        rightOffset: Offset(70, 30),
        rightScale: 0.3,
      ),
      'assets/images/emoji/marshmallow3.png': MascotDecorationConfig(
        leftOffset: Offset(-64, 60),
        leftScale: 0.3,
        rightOffset: Offset(64, 60),
        rightScale: 0.3,
      ),
      'assets/images/emoji/marshmallow4.png': MascotDecorationConfig(
        leftOffset: Offset(-64, 60),
        leftScale: 0.3,
        rightOffset: Offset(64, 60),
        rightScale: 0.3,
      ),
    },
  ),
  MascotDecoration(
    id: 'earring_goodnight_puppy',
    name: '晚安小汪',
    path: 'assets/images/emoji/arrings/arrings5.png',
    leftPath: 'assets/images/emoji/arrings/arrings5_l.png',
    rightPath: 'assets/images/emoji/arrings/arrings5_r.png',
    description: '萌萌的小汪造型耳坠，伴你进入香甜梦乡，治愈每一个安宁夜晚。',
    rarity: MascotRarity.epic,
    category: MascotDecorationCategory.face,
    keepEars: true,
    defaultConfig: MascotDecorationConfig(
      leftOffset: Offset(-55, 30),
      leftScale: 0.65,
      rightOffset: Offset(55, 30),
      rightScale: 0.65,
    ),
    characterConfigs: {
      'assets/images/emoji/marshmallow.png': MascotDecorationConfig(
        leftOffset: Offset(-64, 50),
        leftScale: 0.3,
        rightOffset: Offset(64, 50),
        rightScale: 0.3,
      ),
      'assets/images/emoji/marshmallow2.png': MascotDecorationConfig(
        leftOffset: Offset(-70, 30),
        leftScale: 0.3,
        rightOffset: Offset(70, 30),
        rightScale: 0.3,
      ),
      'assets/images/emoji/marshmallow3.png': MascotDecorationConfig(
        leftOffset: Offset(-64, 60),
        leftScale: 0.3,
        rightOffset: Offset(64, 60),
        rightScale: 0.3,
      ),
      'assets/images/emoji/marshmallow4.png': MascotDecorationConfig(
        leftOffset: Offset(-64, 60),
        leftScale: 0.3,
        rightOffset: Offset(64, 60),
        rightScale: 0.3,
      ),
    },
  ),
  MascotDecoration(
    id: 'earring_sweet_berry_bear_bell',
    name: '甜莓熊铃耳坠',
    path: 'assets/images/emoji/arrings/arrings6.png',
    leftPath: 'assets/images/emoji/arrings/arrings6_l.png',
    rightPath: 'assets/images/emoji/arrings/arrings6_r.png',
    description: '带有甜美草莓装饰的小熊铃铛耳坠，走动时仿佛能听到清脆的铃声。',
    rarity: MascotRarity.epic,
    category: MascotDecorationCategory.face,
    keepEars: true,
    defaultConfig: MascotDecorationConfig(
      leftOffset: Offset(-55, 30),
      leftScale: 0.65,
      rightOffset: Offset(55, 30),
      rightScale: 0.65,
    ),
    characterConfigs: {
      'assets/images/emoji/marshmallow.png': MascotDecorationConfig(
        leftOffset: Offset(-64, 50),
        leftScale: 0.3,
        rightOffset: Offset(64, 50),
        rightScale: 0.3,
      ),
      'assets/images/emoji/marshmallow2.png': MascotDecorationConfig(
        leftOffset: Offset(-70, 30),
        leftScale: 0.3,
        rightOffset: Offset(70, 30),
        rightScale: 0.3,
      ),
      'assets/images/emoji/marshmallow3.png': MascotDecorationConfig(
        leftOffset: Offset(-64, 60),
        leftScale: 0.3,
        rightOffset: Offset(64, 60),
        rightScale: 0.3,
      ),
      'assets/images/emoji/marshmallow4.png': MascotDecorationConfig(
        leftOffset: Offset(-64, 60),
        leftScale: 0.3,
        rightOffset: Offset(64, 60),
        rightScale: 0.3,
      ),
    },
  ),
  MascotDecoration(
    id: 'earring_black_and_orange_cat',
    name: '黑猫与小橘',
    path: 'assets/images/emoji/arrings/arrings7.png',
    leftPath: 'assets/images/emoji/arrings/arrings7_l.png',
    rightPath: 'assets/images/emoji/arrings/arrings7_r.png',
    description: '可爱的小黑猫戴着小橘子帽，趴在大橘子上，给你带来大吉大利的好运气。',
    rarity: MascotRarity.rare,
    category: MascotDecorationCategory.face,
    keepEars: true,
    defaultConfig: MascotDecorationConfig(
      leftOffset: Offset(-55, 30),
      leftScale: 0.65,
      rightOffset: Offset(55, 30),
      rightScale: 0.65,
    ),
    characterConfigs: {
      'assets/images/emoji/marshmallow.png': MascotDecorationConfig(
        leftOffset: Offset(-64, -50),
        leftScale: 0.3,
        rightOffset: Offset(64, -50),
        rightScale: 0.3,
      ),
      'assets/images/emoji/marshmallow2.png': MascotDecorationConfig(
        leftOffset: Offset(-70, 30),
        leftScale: 0.3,
        rightOffset: Offset(70, 30),
        rightScale: 0.3,
      ),
      'assets/images/emoji/marshmallow3.png': MascotDecorationConfig(
        leftOffset: Offset(-64, -50),
        leftScale: 0.3,
        rightOffset: Offset(64, -50),
        rightScale: 0.3,
      ),
      'assets/images/emoji/marshmallow4.png': MascotDecorationConfig(
        leftOffset: Offset(-61, -60),
        leftScale: 0.3,
        rightOffset: Offset(61, -60),
        rightScale: 0.3,
      ),
    },
  ),
];
